import { User, Area, District, Project, AuditLog, NotificationItem } from '../types';

export const INITIAL_USERS: User[] = [
  // National Super Admin
  {
    id: 'usr_super_admin',
    fullName: 'Rev. Dr. Samuel Kwadwo Boakye',
    email: 'admin@thecophq.org',
    phone: '+233 24 412 3456',
    role: 'super_admin',
    status: 'approved',
    titlePrefix: 'Rev. Dr.',
    profilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-01-01T08:00:00Z',
    approvedBy: 'SYSTEM',
    approvedByName: 'General Headquarters',
    approvedAt: '2026-01-01T08:00:00Z',
  },

  // Area Heads (Approved)
  {
    id: 'usr_area_kaneshie',
    fullName: 'Apostle Emmanuel Yaw Gyasi',
    email: 'kaneshie.area@thecophq.org',
    phone: '+233 20 811 2233',
    role: 'area_head',
    status: 'approved',
    titlePrefix: 'Apostle',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    profilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    approvedBy: 'usr_super_admin',
    approvedByName: 'Rev. Dr. Samuel Kwadwo Boakye',
    approvedAt: '2026-01-05T09:30:00Z',
    createdAt: '2026-01-05T08:00:00Z',
  },
  {
    id: 'usr_area_kumasi',
    fullName: 'Apostle Dr. Michael Agyemang Prempeh',
    email: 'kumasi.area@thecophq.org',
    phone: '+233 24 999 8877',
    role: 'area_head',
    status: 'approved',
    titlePrefix: 'Apostle Dr.',
    areaId: 'area_kumasi',
    areaName: 'Kumasi Area',
    profilePhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    approvedBy: 'usr_super_admin',
    approvedByName: 'Rev. Dr. Samuel Kwadwo Boakye',
    approvedAt: '2026-01-06T11:00:00Z',
    createdAt: '2026-01-06T09:15:00Z',
  },
  {
    id: 'usr_area_london',
    fullName: 'Apostle John Kingsley Arthur',
    email: 'london.area@thecophq.org',
    phone: '+44 7700 900123',
    role: 'area_head',
    status: 'approved',
    titlePrefix: 'Apostle',
    areaId: 'area_london',
    areaName: 'London Area',
    profilePhoto: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    approvedBy: 'usr_super_admin',
    approvedByName: 'Rev. Dr. Samuel Kwadwo Boakye',
    approvedAt: '2026-01-10T14:00:00Z',
    createdAt: '2026-01-09T16:00:00Z',
  },

  // Pastors (Approved)
  {
    id: 'usr_pastor_kaneshie_central',
    fullName: 'Pastor Daniel Mensah-Bonsu',
    email: 'pastor.kaneshie@copconnect.org',
    phone: '+233 24 555 4321',
    role: 'pastor',
    status: 'approved',
    titlePrefix: 'Pastor',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    districtId: 'dist_kaneshie_central',
    districtName: 'Kaneshie Central District',
    profilePhoto: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    approvedBy: 'usr_area_kaneshie',
    approvedByName: 'Apostle Emmanuel Yaw Gyasi',
    approvedAt: '2026-01-12T10:00:00Z',
    createdAt: '2026-01-11T12:00:00Z',
  },
  {
    id: 'usr_pastor_bubuashie',
    fullName: 'Pastor Joseph Kwesi Amoah',
    email: 'pastor.bubuashie@copconnect.org',
    phone: '+233 27 666 7788',
    role: 'pastor',
    status: 'approved',
    titlePrefix: 'Pastor',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    districtId: 'dist_bubuashie',
    districtName: 'Bubuashie District',
    profilePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    approvedBy: 'usr_area_kaneshie',
    approvedByName: 'Apostle Emmanuel Yaw Gyasi',
    approvedAt: '2026-01-14T09:00:00Z',
    createdAt: '2026-01-13T15:30:00Z',
  },
  {
    id: 'usr_pastor_asokwa',
    fullName: 'Pastor Stephen Owusu-Ansah',
    email: 'pastor.asokwa@copconnect.org',
    phone: '+233 24 333 9900',
    role: 'pastor',
    status: 'approved',
    titlePrefix: 'Pastor',
    areaId: 'area_kumasi',
    areaName: 'Kumasi Area',
    districtId: 'dist_asokwa',
    districtName: 'Asokwa Central District',
    profilePhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    approvedBy: 'usr_area_kumasi',
    approvedByName: 'Apostle Dr. Michael Agyemang Prempeh',
    approvedAt: '2026-01-15T11:20:00Z',
    createdAt: '2026-01-14T18:00:00Z',
  },
  {
    id: 'usr_pastor_london_central',
    fullName: 'Pastor David Osei-Tutu',
    email: 'pastor.londoncentral@copconnect.org',
    phone: '+44 7891 234567',
    role: 'pastor',
    status: 'approved',
    titlePrefix: 'Pastor',
    areaId: 'area_london',
    areaName: 'London Area',
    districtId: 'dist_london_central',
    districtName: 'London Central (Walthamstow)',
    profilePhoto: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80',
    approvedBy: 'usr_area_london',
    approvedByName: 'Apostle John Kingsley Arthur',
    approvedAt: '2026-01-18T16:00:00Z',
    createdAt: '2026-01-17T11:00:00Z',
  },

  // PENDING ACCOUNTS (for testing verification queue)
  {
    id: 'usr_pending_area_head',
    fullName: 'Apostle Isaac K. Ayani',
    email: 'capecoast.applicant@thecophq.org',
    phone: '+233 24 777 6655',
    role: 'area_head',
    status: 'pending',
    titlePrefix: 'Apostle',
    areaId: 'area_cape_coast',
    areaName: 'Cape Coast Area',
    profilePhoto: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-02-28T14:25:00Z',
  },
  {
    id: 'usr_pending_pastor',
    fullName: 'Pastor Gabriel Antwi Boasiako',
    email: 'darkuman.pastor@copconnect.org',
    phone: '+233 20 444 8899',
    role: 'pastor',
    status: 'pending',
    titlePrefix: 'Pastor',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    districtId: 'dist_darkuman',
    districtName: 'Darkuman District',
    profilePhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    createdAt: '2026-02-29T10:15:00Z',
  }
];

export const INITIAL_AREAS: Area[] = [
  // Greater Accra Region Areas
  {
    id: 'area_kaneshie',
    name: 'Kaneshie Area',
    region: 'Greater Accra',
    country: 'Ghana',
    areaHeadUserId: 'usr_area_kaneshie',
    areaHeadName: 'Apostle Emmanuel Yaw Gyasi',
    areaHeadPhone: '+233 20 811 2233',
    areaHeadEmail: 'kaneshie.area@thecophq.org',
    districtCount: 14,
    totalProjectsCount: 1,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_odorkor',
    name: 'Odorkor Area',
    region: 'Greater Accra',
    country: 'Ghana',
    areaHeadName: 'Apostle Patrick Agyemang Gyebi',
    districtCount: 16,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_madina',
    name: 'Madina Area',
    region: 'Greater Accra',
    country: 'Ghana',
    areaHeadName: 'Apostle Martin Seth Appiah',
    districtCount: 18,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_achimota',
    name: 'Achimota Area',
    region: 'Greater Accra',
    country: 'Ghana',
    areaHeadName: 'Apostle David Tettey Tekper',
    districtCount: 15,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_teshie_nungua',
    name: 'Teshie-Nungua Area',
    region: 'Greater Accra',
    country: 'Ghana',
    areaHeadName: 'Apostle Wilberforce Nkrumah-Agyeman',
    districtCount: 17,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_kasoa',
    name: 'Kasoa Area',
    region: 'Central / Greater Accra Border',
    country: 'Ghana',
    areaHeadName: 'Apostle Ekow Badu Wood',
    districtCount: 20,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_tema',
    name: 'Tema Area',
    region: 'Greater Accra',
    country: 'Ghana',
    areaHeadName: 'Apostle Matthew Larbi Wengam',
    districtCount: 19,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // Ashanti Region Areas
  {
    id: 'area_kumasi',
    name: 'Kumasi Area',
    region: 'Ashanti',
    country: 'Ghana',
    areaHeadUserId: 'usr_area_kumasi',
    areaHeadName: 'Apostle Dr. Michael Agyemang Prempeh',
    areaHeadPhone: '+233 24 999 8877',
    areaHeadEmail: 'kumasi.area@thecophq.org',
    districtCount: 22,
    totalProjectsCount: 1,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_suame',
    name: 'Suame Area',
    region: 'Ashanti',
    country: 'Ghana',
    areaHeadName: 'Apostle John Osei Amaniampong',
    districtCount: 18,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_asokwa',
    name: 'Asokwa Area',
    region: 'Ashanti',
    country: 'Ghana',
    areaHeadName: 'Apostle Prophet James Osei Amaniampong',
    districtCount: 16,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_kwadaso',
    name: 'Kwadaso Area',
    region: 'Ashanti',
    country: 'Ghana',
    areaHeadName: 'Apostle Kingsley Addai',
    districtCount: 15,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_mampong',
    name: 'Mampong Area',
    region: 'Ashanti',
    country: 'Ghana',
    areaHeadName: 'Apostle Samuel Antwi',
    districtCount: 14,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_obuasi',
    name: 'Obuasi Area',
    region: 'Ashanti',
    country: 'Ghana',
    areaHeadName: 'Apostle Francis Ofori-Yeboah',
    districtCount: 17,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // Western Region Areas
  {
    id: 'area_takoradi',
    name: 'Takoradi Area',
    region: 'Western',
    country: 'Ghana',
    areaHeadUserId: '',
    areaHeadName: 'Apostle Samuel Otu Appiah',
    districtCount: 16,
    totalProjectsCount: 1,
    totalCompletedProjects: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_tarkwa',
    name: 'Tarkwa Area',
    region: 'Western',
    country: 'Ghana',
    areaHeadName: 'Apostle Dr. Stephen Baidoo',
    districtCount: 15,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // Central Region Areas
  {
    id: 'area_cape_coast',
    name: 'Cape Coast Area',
    region: 'Central',
    country: 'Ghana',
    areaHeadUserId: 'usr_pending_area_head',
    areaHeadName: 'Apostle Isaac K. Ayani (Pending)',
    districtCount: 14,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_winneba',
    name: 'Winneba Area',
    region: 'Central',
    country: 'Ghana',
    areaHeadName: 'Apostle Isaac Tetteh Judah',
    districtCount: 13,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // Eastern Region Areas
  {
    id: 'area_koforidua',
    name: 'Koforidua Area',
    region: 'Eastern',
    country: 'Ghana',
    areaHeadName: 'Apostle Daniel Frimpong',
    districtCount: 18,
    totalProjectsCount: 1,
    totalCompletedProjects: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_suhum',
    name: 'Suhum Area',
    region: 'Eastern',
    country: 'Ghana',
    areaHeadName: 'Apostle Lawrence Otu-Nyarko',
    districtCount: 14,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // Northern & Upper Regions
  {
    id: 'area_tamale',
    name: 'Tamale Area',
    region: 'Northern',
    country: 'Ghana',
    areaHeadName: 'Apostle Joseph Mensah',
    districtCount: 12,
    totalProjectsCount: 1,
    totalCompletedProjects: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_bolgatanga',
    name: 'Bolgatanga Area',
    region: 'Upper East',
    country: 'Ghana',
    areaHeadName: 'Apostle James Osei',
    districtCount: 11,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_wa',
    name: 'Wa Area',
    region: 'Upper West',
    country: 'Ghana',
    areaHeadName: 'Apostle Robert K. Andoh',
    districtCount: 10,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // Volta & Oti Regions
  {
    id: 'area_ho',
    name: 'Ho Area',
    region: 'Volta',
    country: 'Ghana',
    areaHeadName: 'Apostle Moses Aloba',
    districtCount: 13,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // Bono, Bono East & Ahafo Regions
  {
    id: 'area_sunyani',
    name: 'Sunyani Area',
    region: 'Bono',
    country: 'Ghana',
    areaHeadName: 'Apostle Mark Obeng Andoh',
    districtCount: 16,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_techiman',
    name: 'Techiman Area',
    region: 'Bono East',
    country: 'Ghana',
    areaHeadName: 'Apostle Samuel Osei',
    districtCount: 15,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // International Missions Areas
  {
    id: 'area_london',
    name: 'London Area',
    region: 'United Kingdom',
    country: 'United Kingdom',
    areaHeadUserId: 'usr_area_london',
    areaHeadName: 'Apostle John Kingsley Arthur',
    areaHeadPhone: '+44 7700 900123',
    areaHeadEmail: 'london.area@thecophq.org',
    districtCount: 8,
    totalProjectsCount: 1,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_new_york',
    name: 'New York Area',
    region: 'North America',
    country: 'United States',
    areaHeadName: 'Apostle David Obeng',
    districtCount: 9,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_toronto',
    name: 'Toronto Area',
    region: 'Ontario',
    country: 'Canada',
    areaHeadName: 'Apostle James McKeown Quaye',
    districtCount: 7,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_paris',
    name: 'Paris Area',
    region: 'Western Europe',
    country: 'France',
    areaHeadName: 'Apostle Jean-Pierre Kouassi',
    districtCount: 6,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_lagos',
    name: 'Lagos Area',
    region: 'Lagos State',
    country: 'Nigeria',
    areaHeadName: 'Apostle Emmanuel Olusegun',
    districtCount: 12,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'area_abidjan',
    name: 'Abidjan Area',
    region: 'Lagunes',
    country: 'Côte d\'Ivoire',
    areaHeadName: 'Apostle Yao Kouame',
    districtCount: 10,
    totalProjectsCount: 0,
    totalCompletedProjects: 0,
    createdAt: '2026-01-01T00:00:00Z',
  }
];

export const INITIAL_DISTRICTS: District[] = [
  // Kaneshie Area Districts
  {
    id: 'dist_kaneshie_central',
    name: 'Kaneshie Central District',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    pastorUserId: 'usr_pastor_kaneshie_central',
    pastorName: 'Pastor Daniel Mensah-Bonsu',
    pastorPhone: '+233 24 555 4321',
    assemblyCount: 7,
    projectCount: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dist_bubuashie',
    name: 'Bubuashie District',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    pastorUserId: 'usr_pastor_bubuashie',
    pastorName: 'Pastor Joseph Kwesi Amoah',
    pastorPhone: '+233 27 666 7788',
    assemblyCount: 6,
    projectCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dist_darkuman',
    name: 'Darkuman District',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    pastorUserId: 'usr_pending_pastor',
    pastorName: 'Pastor Gabriel Antwi Boasiako (Pending)',
    pastorPhone: '+233 20 444 8899',
    assemblyCount: 5,
    projectCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dist_abossey_okai',
    name: 'Abossey Okai District',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    pastorName: 'Pastor Richmond Appiah',
    assemblyCount: 4,
    projectCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dist_north_kaneshie',
    name: 'North Kaneshie District',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    pastorName: 'Pastor Benjamin Annan',
    assemblyCount: 6,
    projectCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dist_awudome',
    name: 'Awudome District',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    pastorName: 'Pastor Felix Quaye',
    assemblyCount: 5,
    projectCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // Kumasi Area Districts
  {
    id: 'dist_asokwa',
    name: 'Asokwa Central District',
    areaId: 'area_kumasi',
    areaName: 'Kumasi Area',
    pastorUserId: 'usr_pastor_asokwa',
    pastorName: 'Pastor Stephen Owusu-Ansah',
    pastorPhone: '+233 24 333 9900',
    assemblyCount: 8,
    projectCount: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dist_suame',
    name: 'Suame District',
    areaId: 'area_kumasi',
    areaName: 'Kumasi Area',
    pastorName: 'Pastor Seth Osei-Wusu',
    assemblyCount: 7,
    projectCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dist_bantama',
    name: 'Bantama District',
    areaId: 'area_kumasi',
    areaName: 'Kumasi Area',
    pastorName: 'Pastor Kofi Boateng',
    assemblyCount: 9,
    projectCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dist_kwadaso',
    name: 'Kwadaso District',
    areaId: 'area_kumasi',
    areaName: 'Kumasi Area',
    pastorName: 'Pastor Emmanuel Koduah',
    assemblyCount: 6,
    projectCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // Takoradi Area Districts
  {
    id: 'dist_takoradi_central',
    name: 'Takoradi Central District',
    areaId: 'area_takoradi',
    areaName: 'Takoradi Area',
    pastorName: 'Pastor Enoch Baafi',
    assemblyCount: 8,
    projectCount: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dist_effia_kuma',
    name: 'Effia-Kuma District',
    areaId: 'area_takoradi',
    areaName: 'Takoradi Area',
    pastorName: 'Pastor Jonathan Sackey',
    assemblyCount: 6,
    projectCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
  },

  // London Area Districts
  {
    id: 'dist_london_central',
    name: 'London Central (Walthamstow)',
    areaId: 'area_london',
    areaName: 'London Area',
    pastorUserId: 'usr_pastor_london_central',
    pastorName: 'Pastor David Osei-Tutu',
    pastorPhone: '+44 7891 234567',
    assemblyCount: 5,
    projectCount: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dist_south_london',
    name: 'South London District',
    areaId: 'area_london',
    areaName: 'London Area',
    pastorName: 'Pastor Matthew Jenkins',
    assemblyCount: 4,
    projectCount: 0,
    createdAt: '2026-01-01T00:00:00Z',
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj_kaneshie_cathedral',
    title: '5,000-Seater Central Cathedral & Ministry Complex Construction',
    category: 'Church Building',
    description: 'Construction of the new state-of-the-art multi-tier auditorium for Kaneshie Central. Includes 5,000-capacity main auditorium, children ministry suites, modern audiovisual broadcast room, executive conference rooms, and 200-vehicle underground parking facility. Currently roofing structure and glass curtain installation are actively underway.',
    status: 'Ongoing',
    photos: [
      'https://images.unsplash.com/photo-1548625361-195fe614b749?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1000&auto=format&fit=crop&q=80'
    ],
    fundingProgress: 68,
    targetBudget: 4500000,
    raisedBudget: 3060000,
    currency: 'GHS',
    areaId: 'area_kaneshie',
    areaName: 'Kaneshie Area',
    districtId: 'dist_kaneshie_central',
    districtName: 'Kaneshie Central District',
    postedByUserId: 'usr_pastor_kaneshie_central',
    postedByName: 'Pastor Daniel Mensah-Bonsu',
    postedByRole: 'pastor',
    postedByTitle: 'Pastor',
    location: 'Kaneshie Highway Junction, Accra',
    startDate: '2025-03-15',
    targetCompletionDate: '2026-12-20',
    likes: ['usr_super_admin', 'usr_area_kumasi', 'usr_pastor_asokwa'],
    milestones: [
      { id: 'm1', title: 'Land Acquisition & Architectural Approvals', completed: true, completedAt: '2025-02-10' },
      { id: 'm2', title: 'Foundation & Substructure Concrete Pouring', completed: true, completedAt: '2025-06-25' },
      { id: 'm3', title: 'Superstructure Pillars & Gallery Beams', completed: true, completedAt: '2025-11-30' },
      { id: 'm4', title: 'Roof Truss Installation & Acoustic Paneling', completed: false },
      { id: 'm5', title: 'Interior Tiling, Seating & Audio/Visual Setup', completed: false }
    ],
    comments: [
      {
        id: 'c1',
        projectId: 'proj_kaneshie_cathedral',
        userId: 'usr_area_kumasi',
        userName: 'Apostle Dr. Michael Agyemang Prempeh',
        userRole: 'area_head',
        userAreaName: 'Kumasi Area',
        content: 'Glory to God! A massive and inspiring edifice for the kingdom. The Kumasi Area leadership celebrates this milestone with Kaneshie Area.',
        type: 'encouragement',
        createdAt: '2026-02-10T14:30:00Z'
      },
      {
        id: 'c2',
        projectId: 'proj_kaneshie_cathedral',
        userId: 'usr_super_admin',
        userName: 'Rev. Dr. Samuel Kwadwo Boakye',
        userRole: 'super_admin',
        content: 'Commendable progress Pastor Daniel and the District Executive Committee. Keep up the high standard of construction and financial stewardship.',
        type: 'comment',
        createdAt: '2026-02-15T09:10:00Z'
      }
    ],
    statusUpdates: [
      {
        id: 'su_1',
        previousStatus: 'Planned',
        newStatus: 'Ongoing',
        note: 'Contract awarded and heavy machinery broke ground on site.',
        updatedBy: 'Pastor Daniel Mensah-Bonsu',
        updatedAt: '2025-03-15T10:00:00Z'
      }
    ],
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-02-20T16:45:00Z'
  },

  {
    id: 'proj_afram_plains_outreach',
    title: 'National Mega Rural Evangelism & Medical Outreach (Afram Plains)',
    category: 'Outreach/Evangelism',
    description: 'A 5-day intensive gospel crusade across 18 island villages in the Afram Plains riverine basin. Mobilized 120 evangelism personnel, 15 medical doctors, and distributed 3,000 free Bibles and healthcare packages. Resulted in 1,420 souls won and 4 new Local Assemblies inaugurated.',
    status: 'Completed',
    photos: [
      'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1000&auto=format&fit=crop&q=80'
    ],
    fundingProgress: 100,
    targetBudget: 280000,
    raisedBudget: 280000,
    currency: 'GHS',
    areaId: 'area_koforidua',
    areaName: 'Koforidua Area',
    postedByUserId: 'usr_super_admin',
    postedByName: 'Apostle Daniel Frimpong',
    postedByRole: 'area_head',
    postedByTitle: 'Apostle',
    location: 'Donkorkrom & Island Communities, Eastern Region',
    startDate: '2026-01-20',
    targetCompletionDate: '2026-01-25',
    completedDate: '2026-01-25',
    likes: ['usr_area_kaneshie', 'usr_pastor_kaneshie_central', 'usr_area_london'],
    milestones: [
      { id: 'm10', title: 'Volunteer Registration & Orientation', completed: true, completedAt: '2026-01-10' },
      { id: 'm11', title: 'Medical Supply Procurement & Logistics', completed: true, completedAt: '2026-01-15' },
      { id: 'm12', title: 'Island Crusade Nights & Door-to-Door Rallies', completed: true, completedAt: '2026-01-24' },
      { id: 'm13', title: 'Converts Follow-up & Assembly Plantings', completed: true, completedAt: '2026-01-25' }
    ],
    comments: [],
    createdAt: '2026-01-26T12:00:00Z',
    updatedAt: '2026-01-26T12:00:00Z'
  },

  {
    id: 'proj_asokwa_youth_hub',
    title: 'Pentecost Youth Innovation & Vocational Training Hub',
    category: 'Community Project',
    description: 'Establishment of a 2-storey digital literacy and vocational skills center equipped with 50 high-end computers, coding labs, tailoring training workshops, and an incubator for young church entrepreneurs across the Ashanti Region.',
    status: 'Ongoing',
    photos: [
      'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1000&auto=format&fit=crop&q=80'
    ],
    fundingProgress: 52,
    targetBudget: 850000,
    raisedBudget: 442000,
    currency: 'GHS',
    areaId: 'area_kumasi',
    areaName: 'Kumasi Area',
    districtId: 'dist_asokwa',
    districtName: 'Asokwa Central District',
    postedByUserId: 'usr_pastor_asokwa',
    postedByName: 'Pastor Stephen Owusu-Ansah',
    postedByRole: 'pastor',
    postedByTitle: 'Pastor',
    location: 'Asokwa Church Premises, Kumasi',
    startDate: '2025-08-01',
    targetCompletionDate: '2026-09-30',
    likes: ['usr_super_admin', 'usr_area_kaneshie'],
    comments: [],
    createdAt: '2026-01-16T14:20:00Z',
    updatedAt: '2026-02-18T10:00:00Z'
  },

  {
    id: 'proj_tamale_boreholes',
    title: 'Clean Water Borehole Initiative (10 Rural Assemblies)',
    category: 'Community Project',
    description: 'Drilling and mechanization of 10 solar-powered potable water boreholes in arid rural communities in the Northern Region. Serving over 15,000 community members and church congregants who previously walked over 5km for water.',
    status: 'Completed',
    photos: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1000&auto=format&fit=crop&q=80'
    ],
    fundingProgress: 100,
    targetBudget: 350000,
    raisedBudget: 350000,
    currency: 'GHS',
    areaId: 'area_tamale',
    areaName: 'Tamale Area',
    postedByUserId: 'usr_super_admin',
    postedByName: 'Apostle Joseph Mensah',
    postedByRole: 'area_head',
    postedByTitle: 'Apostle',
    location: 'Savelugu, Tolon & Kumbungu Districts, Northern Region',
    startDate: '2025-10-01',
    targetCompletionDate: '2026-01-15',
    completedDate: '2026-01-15',
    likes: ['usr_area_kaneshie', 'usr_area_kumasi'],
    comments: [],
    createdAt: '2026-01-18T09:00:00Z',
    updatedAt: '2026-01-18T09:00:00Z'
  },

  {
    id: 'proj_london_youth_conf',
    title: 'Global Pentecost Youth All-Nations Conference 2026',
    category: 'Conference/Event',
    description: 'An international youth leadership symposium bringing together over 2,500 delegates from UK, Europe, and North America for deep biblical discipleship, leadership masterclasses, and global mission mobilization.',
    status: 'Planned',
    photos: [
      'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1000&auto=format&fit=crop&q=80'
    ],
    fundingProgress: 35,
    targetBudget: 75000,
    raisedBudget: 26250,
    currency: 'GBP',
    areaId: 'area_london',
    areaName: 'London Area',
    districtId: 'dist_london_central',
    districtName: 'London Central (Walthamstow)',
    postedByUserId: 'usr_pastor_london_central',
    postedByName: 'Pastor David Osei-Tutu',
    postedByRole: 'pastor',
    postedByTitle: 'Pastor',
    location: 'Excel London Convention Center, UK',
    startDate: '2026-07-15',
    targetCompletionDate: '2026-07-19',
    likes: ['usr_area_london'],
    comments: [],
    createdAt: '2026-02-01T15:00:00Z',
    updatedAt: '2026-02-01T15:00:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_1',
    actorId: 'usr_super_admin',
    actorName: 'Rev. Dr. Samuel Kwadwo Boakye',
    actorRole: 'super_admin',
    action: 'AREA_HEAD_APPROVED',
    targetId: 'usr_area_kaneshie',
    targetName: 'Apostle Emmanuel Yaw Gyasi (Kaneshie Area)',
    details: 'Verified credentials and assigned leadership over Kaneshie Area.',
    timestamp: '2026-01-05T09:30:00Z'
  },
  {
    id: 'log_2',
    actorId: 'usr_area_kaneshie',
    actorName: 'Apostle Emmanuel Yaw Gyasi',
    actorRole: 'area_head',
    action: 'PASTOR_APPROVED',
    targetId: 'usr_pastor_kaneshie_central',
    targetName: 'Pastor Daniel Mensah-Bonsu (Kaneshie Central)',
    details: 'Approved pastoral registration and assigned to Kaneshie Central District.',
    timestamp: '2026-01-12T10:00:00Z'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'usr_area_kaneshie',
    title: 'New Pastor Approval Request',
    message: 'Pastor Gabriel Antwi Boasiako has requested to register for Darkuman District.',
    type: 'approval',
    read: false,
    link: '/area-head?tab=approvals',
    createdAt: '2026-02-29T10:15:00Z'
  },
  {
    id: 'notif_2',
    userId: 'usr_super_admin',
    title: 'New Area Head Verification Request',
    message: 'Apostle Isaac K. Ayani has applied to register Cape Coast Area.',
    type: 'approval',
    read: false,
    link: '/admin?tab=approvals',
    createdAt: '2026-02-28T14:25:00Z'
  }
];
